name: Publish to Modrinth
on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update pack version
        run: |
          jq --arg version "${{ github.event.release.tag_name }}" '.pack.description[7].text = $version' pack.mcmeta > pack.mcmeta.tmp && mv pack.mcmeta.tmp pack.mcmeta

      - name: Zip Datapack
        run: zip -r Grid-DP_v${{ github.event.release.tag_name }}.zip . -x ".github/*" ".git/*" "*.yml" "README.md" # Package files into .zip

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: "uOme8XHr"
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          files: "Grid-DP_v${{ github.event.release.tag_name }}.zip"
          loaders: "datapack"
          game-versions: |-
            26.2
          channel: ${{ github.event.release.prerelease && 'beta' || 'release' }}

      - name: Send Discord notification
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg body "${{ github.event.release.body }}\n\n-# [Contribute](https://github.com/ocoralznn/grid) · [Report a bug](https://github.com/ocoralznn/grid/issues)" \
              --arg name "${{ github.event.release.name }}" \
              --arg tag "${{ github.event.release.tag_name }}" \
              '{
                "embeds": [
                  {
                    "thumbnail": {
                      "url": "https://cdn.modrinth.com/data/uOme8XHr/9832cbf9f0526669985beb1159eec6ef37e8ef50_96.webp"
                    },
                    "title": $tag,
                    "color": 16750092,
                    "description": $body,
                    "footer": {
                      "text": "Presented to YOU",
                      "icon_url": "https://raw.githubusercontent.com/ChoirStudios/ChoirStudios.github.io/refs/heads/main/assets/logo.png"
                    }
                  }
                ],
                "components": [
                  {
                    "type": 1,
                    "components": [
                      {
                        "type": 2,
                        "style": 5,
                        "url": "https://modrinth.com/datapack/grid-from-choir/versions",
                        "custom_id": "p_316545653821935617",
                        "label": "Download"
                      }
                    ]
                  }
                ],
                "thread_name": $name
              }'
            )"
