name: Publish to Modrinth
on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip Datapack
        run: zip -r Grid.zip . -x ".github/*" ".git/*" "*.yml" "README.md" # Package files into .zip

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: "uOme8XHr"
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          files: "Grid.zip"
          loaders: "datapack"
          game-versions: |-
            26.2
          channel: "release"
